Updates code of conduct
codefellows/code-of-conduct pull request #13
Opened 2023-03-10 03:08 UTC by brookr

2023-03-20 18:46 UTC, Rapparicio approved these changes
Looks good

2023-03-20 19:35 UTC, johncokos commented on README.md
> +- **Be respectful**: Not all of us will agree all of the time, but disagreement is no excuse for poor behavior and poor manners. We might all experience some frustration now and then, but we cannot a
"is not a productive one" ...

This is a good opportunity to fold in the words "psychologically safe" - Maybe something like "is not a psychologically safe and therefore unproductive environment"

Just spitballing

2023-03-20 19:38 UTC, johncokos commented on README.md
> +- **Be respectful**: Not all of us will agree all of the time, but disagreement is no excuse for poor behavior and poor manners. We might all experience some frustration now and then, but we cannot a
Also "give others the benefit of the doubt" might also include some language about space. Maybe something like 

"Choose patience, and provide others the space needed to think and speak, giving the benefit of the doubt whenever you can"

2023-03-20 21:15 UTC, JB-Tellez commented on README.md
> +- **Be respectful**: Not all of us will agree all of the time, but disagreement is no excuse for poor behavior and poor manners. We might all experience some frustration now and then, but we cannot a
"**Be considerate**: Any decision you take will affect users and colleagues" 

replace "Any decision you take" with "Actions you take" or "Your words and actions will affect". Something to distinguish from "I made an internal decision to have Mexican vs. Thai for dinner tonight" ;)

2023-03-20 21:19 UTC, JB-Tellez commented on README.md
> +- **Give attribution, engage honestly**: Since the quality of our work often depends on the contributions of others, we strive to give proper attribution to all sources used, including chatbots, web
Replace "claim only work that is our won" with "to only claim that is our own"

2023-03-20 23:23 UTC, johncokos requested changes

2023-03-21 16:45 UTC, johncokos approved these changes

2023-03-22 20:40 UTC, merged